### ISSUE TITLE
Embed DiffEqTutorials and DiffEqBenchmarks?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqDocs.jl#313]
Now that we can have an accordion on the sidebar, I was wondering if it was possible to embed the generated HTMLs of these two libraries into the documentation, to make it a better "one stop shop" without overloading on content.

@kanav99 do you think this might be possible?

**Comment by kanav99** [comment]
We can have a new section for interactive tutorials and benchmarks, we can run julia code in Documenter too. We can in fact plug the output from Weave.jl inside the body of Documentation, but I am pretty sure that would look awful as both of them have different frontends and different usage. 

IMO what we can do is copying the `.jmd` files into a new section `interactive tutorials` and run the Julia codes using @example block in Documenter (https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@example-block-1).

The case of benchmarks would be tricky because we can't run it on the CI. We would need to write a nice scrapper for it. It seems like an interesting project to me and probably useful for the community too.

**Comment by ChrisRackauckas** [comment]
Fixed by the new docs
