### ISSUE TITLE
Complex Gaussian noise in SDE

### ISSUE THREAD

**Issue by anirudhpammi** [SciML/DiffEqDocs.jl#375]
How can I introduce noise of the form (randn()+im*randn())/sqrt(2) in my complex variables? I checked the documentation but I didn't understand the implementation. I tried copying the code from the example but the function DiffEqBase.wiener_randn() isn't defined. Did someone have a similar issue?
Thanks!

**Comment by ChrisRackauckas** [comment]
That happens by default if you use complex valued numbers as your initial condition to the SDE solver. 

I'll close this because there's nothing else to do (since it is the default), but feel free to continue asking questions if you have any. These kinds of questions are good to ask on the Julia Discourse (https://discourse.julialang.org/) or the Slack (https://slackinvite.julialang.org/) (in case you haven't found those resources yet)
