### ISSUE TITLE
A  question about the parameter function

### ISSUE THREAD

**Issue by HaojieZhang917** [SciML/DiffEqDocs.jl#756]
**Question❓**
There is a example about solving **nonhomogeneous equations** using parameter function in the tutorials.In that case,parameter is introduced as a function which is time-varying like this.
`M = t -> 0.1sin(t)`
`prob = ODEProblem(pendulum!, u₀, tspan, M)`
But in my ODE,there is **four time-varying parameter equations** needed to introduce.I try to introduce the parameter function as a tuple which include four time-varying parameter equations,but it seems wrong.
So what can i do to  solve this question?

**Comment by ChrisRackauckas** [comment]
Is there any reason for not just using it as a standard generic function? Just make `M(t) = 0.1sin(t)` and use it in `f`?

You could also just make it a tuple, and that's type-stable for indexing, but I don't see why you wouldn't just make generic functions.

Closing since there isn't a change to the docs to be made, but feel free to continue the conversation. Or discourse.julialang.org might be a good place to discuss this.
